#!/bin/bash

if [ -z "$(pgrep gnome-settings-daemon)" ] ; then
  eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
 export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK
fi

#if [ -z "$(pgrep trayer)" ] ; then
#  trayer --edge top --align right --height 24 --expand false --width 150 --widthtype request --tint 0x000000&
#fi

/home/dewoller/bin/tray &

if [ -z "$(pgrep fluxgui)" ] ; then
    [ -f /tmp/fluxgui_dewoller.pid ] && rm /tmp/fluxgui_dewoller.pid 
    fluxgui &
fi

if [ -z "$(pgrep skype)" ] ; then
    skype &
fi

if [ -z "$(pgrep pavucontrol)" ] ; then
    pavucontrol &
fi


pkill gnome-panel
gnome-panel &
  
if [ -z "$(pgrep syncwall)" ] ; then
    syncwall &
fi
if [ -z "$(pgrep pidgin)" ] ; then
    pidgin  &
fi

if [ -z "$(pgrep dropbox)" ] ; then
    dropbox start &
fi

if [ -z "$(pgrep keepassx)" ] ; then
    keepassx &
fi

if [ -z "$(pgrep firefox)" ] ; then
    firefox &
fi

if [ -z "$(pgrep bluetooth-applet)" ] ; then
    bluetooth-applet &
fi

if [ -z "$(pgrep -c indicator-cpufreq)" ] ; then
    indicator-cpufreq &
fi

if [ -z "$(pgrep syndaemon)" ] ; then
    syndaemon -d -t&
fi

if [ -z "$(pgrep skype)" ] ; then
    skype /secondary /minimized&
fi

if [ -z "$(pgrep -c /opt/google/chrome/chrome)" ] ; then
    chromium-browser &
fi

if [ -z "$(pgrep thunderbird)" ] ; then
    thunderbird &
fi

if [ -z "$(pgrep gnome-terminal)" ] ; then
    gnome-terminal &
fi
# Network manager, so we don't have to configure wifi at the command line.
if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet --sm-disable &
fi

# Applet for managing print jobs from the tray.
if [ -z "$(pgrep system-config-printer-applet)" ] ; then
    system-config-printer-applet &
fi

#
# APPLICATION LAUNCHER
#

# Use synapse as our app launcher. (-s: don't display until requested) 
if [ -z "$(pgrep synapse)" ] ; then
    synapse -s &
fi

# On login, we unlock the ssh keychain so we're not prompted for 
# passphrases later. We pipe /dev/null to ssh-add to make it realize 
# it's not running in a terminal. Otherwise, it won't launch the prompt.
# 
# If you don't use the ssh keychain you may not want this. Commented
# by default as it is assumed many users will not want this feature.

 export SSH_ASKPASS="/usr/bin/ssh-askpass"
 cat /dev/null | ssh-add &

# I disable the middle mouse button because otherwise I constantly 
# accidentally paste unwanted text in the middle of my code while scrolling. 
# Note that the id of the mouse device may be different depending on 
# which usb port it is plugged into! To find it, use:
# xinput list |grep 'id='
# In the following command, the id is the first argument, the rest is 
# the remapping.

# Commented by default as it is assumed many users will not want this.
# xinput set-button-map 10 1 0 3 4 5 6 7

